# LittleFencer iOS - MediaPipe CocoaPods Configuration
# Run 'pod install' after creating this file

platform :ios, '15.0'
use_frameworks!

target 'LittleFencer' do
  # MediaPipe Tasks Vision SDK - Provides 33-point pose detection
  pod 'MediaPipeTasksVision', '~> 0.10.10'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
